// =============================================================================
// modules/playlists.js — Module 7: Playlists (Sets)
// =============================================================================
// Endpoints tested:
//   POST   /playlists           — Create a new playlist
//   GET    /playlists/:id       — Fetch playlist with tracks
//   PATCH  /playlists/:id       — Update playlist metadata
//   PUT    /playlists/:id/tracks — Replace track sequence
//   DELETE /playlists/:id       — Delete playlist (cleanup)
// =============================================================================

import http from "k6/http";
import { check, group, sleep } from "k6";
import { authHeaders, parseJson, pick } from "../helpers.js";

const GENRES     = ["Electronic", "House", "Techno", "Lo-Fi", "Hip-Hop", "Jazz"];
const TAGS       = ["chill", "late-night", "vibes", "fire", "deep", "study"];
const TITLES     = ["Late Night Set", "Chill Mix", "Road Trip Vibes", "Studio Session", "Deep Cuts"];

export function playlistsModule(data) {
  group("7 Playlists", function () {

    // ── 7a. POST Create Playlist ──────────────────────────────────────────────
    // Creates a new playlist document. Immediately extracts the new playlistId
    // to use in subsequent requests within this iteration (data correlation).
    const createRes = http.post(
      `${data.baseUrl}/playlists`,
      JSON.stringify({
        title:       `${pick(TITLES)} ${Date.now()}`,
        description: "Generated by BioBeats stress test",
        genre:       pick(GENRES),
        tags:        [pick(TAGS), pick(TAGS)],
        isPrivate:   false,
        releaseType: "playlist",
      }),
      authHeaders(data.token)
    );
    check(createRes, {
      "Playlists | Create: status 201":             (r) => r.status === 201,
      "Playlists | Create: playlistId returned":    (r) =>
        typeof parseJson(r)?.data?.playlist?._id === "string",
      "Playlists | Create: response < 600ms":       (r) => r.timings.duration < 600,
    });

    // ── Correlate: grab fresh playlistId ─────────────────────────────────────
    // If creation succeeded, use the new ID for the rest of this group.
    // Otherwise fall back to the seeded TARGET_PLAYLIST_ID for read-only tests.
    const newPlaylistId = parseJson(createRes)?.data?.playlist?._id || data.playlistId;
    sleep(1);

    // ── 7b. GET Playlist ──────────────────────────────────────────────────────
    const getRes = http.get(
      `${data.baseUrl}/playlists/${newPlaylistId}`,
      authHeaders(data.token)
    );
    check(getRes, {
      "Playlists | GET: status 200":                (r) => r.status === 200,
      "Playlists | GET: playlist object returned":  (r) => !!parseJson(r)?.data?.playlist,
      "Playlists | GET: response < 500ms":          (r) => r.timings.duration < 500,
    });
    sleep(1);

    // ── 7c. PATCH Update Metadata ─────────────────────────────────────────────
    // Only runs if creation succeeded — we can only edit our own playlist.
    if (createRes.status === 201) {
      const patchRes = http.patch(
        `${data.baseUrl}/playlists/${newPlaylistId}`,
        JSON.stringify({
          title:     `Updated ${pick(TITLES)}`,
          genre:     pick(GENRES),
          isPrivate: false,
        }),
        authHeaders(data.token)
      );
      check(patchRes, {
        "Playlists | Update: status 200":       (r) => r.status === 200,
        "Playlists | Update: response < 500ms": (r) => r.timings.duration < 500,
      });
      sleep(1);

      // ── 7d. PUT Track Sequence ─────────────────────────────────────────────
      // Replaces the tracks array. Using the seeded TARGET_TRACK_ID as the single track.
      // In a real test with multiple seeded tracks, pass all their IDs here.
      const seqRes = http.put(
        `${data.baseUrl}/playlists/${newPlaylistId}/tracks`,
        JSON.stringify({ tracks: [data.trackId] }),
        authHeaders(data.token)
      );
      check(seqRes, {
        "Playlists | Track Sequence: status 200":       (r) => r.status === 200,
        "Playlists | Track Sequence: response < 600ms": (r) => r.timings.duration < 600,
      });
      sleep(1);

      // ── 7e. DELETE Playlist (Cleanup) ──────────────────────────────────────
      // Always clean up playlists we created to keep the DB tidy across iterations.
      // 204 = deleted, 404 = already gone (race condition in rapid tests — OK).
      const deleteRes = http.del(
        `${data.baseUrl}/playlists/${newPlaylistId}`,
        null,
        authHeaders(data.token)
      );
      check(deleteRes, {
        "Playlists | Delete: status 204 or 404": (r) => [204, 404].includes(r.status),
        "Playlists | Delete: response < 500ms":  (r) => r.timings.duration < 500,
      });
    }
    sleep(2);
  });
}
